# Generated by Django 2.2.3 on 2020-03-07 19:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=128)),
                ('species', models.CharField(max_length=128)),
                ('info', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to='petPedia_image')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 19, 44, 784422, tzinfo=utc))),
                ('age', models.IntegerField()),
                ('bio', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('sellCount', models.IntegerField(default=0)),
                ('profilePicture', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=128)),
                ('datePosted', models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 19, 44, 785081, tzinfo=utc))),
                ('postImage', models.ImageField(upload_to='post_image')),
                ('postDescription', models.CharField(max_length=300)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawbook.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePosted', models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 19, 44, 786033, tzinfo=utc))),
                ('petName', models.CharField(max_length=128)),
                ('petAge', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('petImage', models.ImageField(upload_to='listing_image')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawbook.PetPedia')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawbook.UserProfile')),
            ],
        ),
    ]
