# Generated by Django 2.2.3 on 2020-03-07 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datePosted',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 20, 29, 263343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 20, 29, 262270, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateJoined',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 20, 29, 261362, tzinfo=utc)),
        ),
    ]
