# Generated by Django 2.2.3 on 2020-03-07 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0002_auto_20200307_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datePosted',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 20, 49, 770906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 20, 49, 769733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateJoined',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 20, 49, 769083, tzinfo=utc)),
        ),
    ]
