# Generated by Django 2.2.3 on 2020-03-07 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0003_auto_20200307_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datePosted',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 21, 9, 757301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 21, 9, 756139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateJoined',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 19, 21, 9, 755491, tzinfo=utc)),
        ),
    ]
