# Generated by Django 2.2.3 on 2020-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0004_auto_20200307_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datePosted',
            field=models.DateField(verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateField(verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateJoined',
            field=models.DateField(verbose_name='Date Joined'),
        ),
    ]
