# Generated by Django 2.2.3 on 2020-03-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0005_auto_20200307_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='datePosted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='petImage',
            field=models.ImageField(blank=True, upload_to='listing_image'),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='picture',
            field=models.ImageField(blank=True, upload_to='petPedia_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateJoined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sellCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
