# Generated by Django 2.2.3 on 2020-03-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0006_auto_20200308_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='petAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='petImage',
            field=models.ImageField(blank=True, default=None, upload_to='listing_image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='petName',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='breed',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='info',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='petPedia_image'),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='species',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='postDescription',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, default=None, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTitle',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default=None, upload_to='profile_image'),
        ),
    ]
