# Generated by Django 2.2.3 on 2020-03-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0007_auto_20200308_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
