# Generated by Django 2.2.3 on 2020-03-08 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0008_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='petName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='listing',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='breed',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='info',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='species',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='postDescription',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTitle',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
