# Generated by Django 2.2.3 on 2020-03-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0010_remove_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawbook.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawbook.UserProfile'),
        ),
    ]
