# Generated by Django 2.2.3 on 2020-03-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0011_auto_20200323_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='breed',
            field=models.CharField(max_length=128),
        ),
    ]
