# Generated by Django 2.2.3 on 2020-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0012_auto_20200323_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpedia',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
