# Generated by Django 2.2.3 on 2020-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0013_petpedia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
