# Generated by Django 2.2.3 on 2020-03-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0017_auto_20200327_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpedia',
            name='picture',
            field=models.ImageField(blank=True, default=None, storage='/home/p/Desktop/Filez/ScHool/UniGlasgow/YearTwo/Semester 2/Web Apps/Group/pawbook_wad/media/petPedia_image/', upload_to='petPedia_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default=None, storage='/home/p/Desktop/Filez/ScHool/UniGlasgow/YearTwo/Semester 2/Web Apps/Group/pawbook_wad/media/profile_image/', upload_to='profile_image'),
        ),
    ]
