# Generated by Django 2.2.3 on 2020-04-02 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pawbook', '0024_auto_20200402_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commenet',
            new_name='Comment',
        ),
    ]
