# Generated by Django 2.2.3 on 2020-04-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0021_auto_20200402_1331'),
        ('pawbook', '0025_auto_20200402_2100'),
    ]

    operations = [
    ]
