# Generated by Django 2.2.3 on 2020-04-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0027_auto_20200402_2104'),
        ('pawbook', '0026_merge_20200402_1940'),
    ]

    operations = [
    ]
