# Generated by Django 2.2.3 on 2020-04-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0027_auto_20200402_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
