# Generated by Django 2.2.3 on 2020-04-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0028_delete_userpreference'),
        ('pawbook', '0026_merge_20200402_1940'),
    ]

    operations = [
    ]
