# Generated by Django 2.2.3 on 2020-04-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0028_merge_20200402_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='petImage',
            field=models.ImageField(storage='/home/p/Desktop/Filez/ScHool/UniGlasgow/YearTwo/Semester 2/Web Apps/Group/pawbook_wad/media/listing_image/', upload_to='listing_image'),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='picture',
            field=models.ImageField(blank=True, default=None, storage='/home/p/Desktop/Filez/ScHool/UniGlasgow/YearTwo/Semester 2/Web Apps/Group/pawbook_wad/media/petPedia_image/', upload_to='petPedia_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(storage='/home/p/Desktop/Filez/ScHool/UniGlasgow/YearTwo/Semester 2/Web Apps/Group/pawbook_wad/media/post_image/', upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default=None, storage='/home/p/Desktop/Filez/ScHool/UniGlasgow/YearTwo/Semester 2/Web Apps/Group/pawbook_wad/media/profile_image/', upload_to='profile_image'),
        ),
    ]
