# Generated by Django 2.2.3 on 2020-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0030_auto_20200403_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpedia',
            name='picture',
            field=models.ImageField(blank=True, storage='petPedia_image/', upload_to='petPedia_image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, storage='profile_image/', upload_to='profile_image/'),
        ),
    ]
