# Generated by Django 2.2.3 on 2020-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0028_merge_20200402_2257'),
        ('pawbook', '0032_auto_20200403_1944'),
    ]

    operations = [
    ]
