# Generated by Django 2.2.3 on 2020-04-03 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pawbook', '0033_merge_20200403_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='petImage',
            field=models.ImageField(storage='D:\\pawbook_wad\\media/listing_image/', upload_to='listing_image'),
        ),
        migrations.AlterField(
            model_name='petpedia',
            name='picture',
            field=models.ImageField(blank=True, default=None, storage='D:\\pawbook_wad\\media/petPedia_image/', upload_to='petPedia_image'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(storage='D:\\pawbook_wad\\media/post_image/', upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default=None, storage='D:\\pawbook_wad\\media/profile_image/', upload_to='profile_image'),
        ),
    ]
