# Generated by Django 2.2.3 on 2020-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0035_auto_20200403_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, default='profile_image/default.jpg', null=True, upload_to='profile_image'),
        ),
    ]
