# Generated by Django 2.2.3 on 2020-04-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawbook', '0036_auto_20200403_2155'),
        ('pawbook', '0036_auto_20200403_1313'),
    ]

    operations = [
    ]
